"""
==========================================================
PaperBridge
PDF Report Generator
==========================================================

Generate PDF analysis report.

Author  : Al Akbar Himawan
Version : 1.0
==========================================================
"""

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


class ReportGenerator:

    def __init__(
        self,
        resume_data,
        ats_score,
        career_result,
        skill_gap
    ):

        self.resume = resume_data
        self.ats = ats_score
        self.career = career_result
        self.skill_gap = skill_gap

    def generate(self, output_path):

        styles = getSampleStyleSheet()

        doc = SimpleDocTemplate(output_path)

        story = []

        # =====================================
        # TITLE
        # =====================================

        story.append(
            Paragraph(
                "<b>PaperBridge Analysis Report</b>",
                styles["Title"]
            )
        )

        story.append(Spacer(1, 20))

        # =====================================
        # RESUME INFO
        # =====================================

        story.append(
            Paragraph("<b>Candidate Information</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(f"Name : {self.resume['name']}", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Email : {self.resume['email']}", styles["BodyText"])
        )

        story.append(
            Paragraph(f"Phone : {self.resume['phone']}", styles["BodyText"])
        )

        story.append(Spacer(1, 12))

        # =====================================
        # ATS
        # =====================================

        story.append(
            Paragraph("<b>ATS Score</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(
                f"Overall Score : {self.ats['total']} / 100",
                styles["BodyText"]
            )
        )

        story.append(Spacer(1, 12))

        # =====================================
        # CAREER
        # =====================================

        story.append(
            Paragraph("<b>Top Career Match</b>", styles["Heading2"])
        )

        for job in self.career:

            story.append(

                Paragraph(

                    f"{job['job_title']} ({job['match_score']}%)",

                    styles["BodyText"]

                )

            )

        story.append(Spacer(1, 12))

        # =====================================
        # SKILL GAP
        # =====================================

        story.append(
            Paragraph("<b>Skill Gap</b>", styles["Heading2"])
        )

        if self.skill_gap:

            for skill in self.skill_gap:

                story.append(

                    Paragraph(

                        f"• {skill}",

                        styles["BodyText"]

                    )

                )

        else:

            story.append(

                Paragraph(

                    "No significant skill gap detected.",

                    styles["BodyText"]

                )

            )

        story.append(Spacer(1, 20))

        story.append(

            Paragraph(

                "Generated by PaperBridge",

                styles["Italic"]

            )

        )

        doc.build(story)